language: node_js
node_js:
  - 'stable'
  - '16'
  - '14'
  - '12'

cache:
  directories:
    - node_modules

# Set INIT_CWD for Husky due to Npm 7 not including it.
before_install:
  - export INIT_CWD="$(pwd)"

# Lint errors should trigger a failure.
before_script: npm run lint && npm run build

# Code coverage
script: npm run coveralls
